---
- name: Configure R1 with subnets and OSPF
  hosts: R1
  gather_facts: false
  tasks:
    - name: Configure OSPF process
      ios_config:
        lines:
          - router ospf 1
    - name: Configure G0/0
      ios_config:
        lines:
          - ip address 10.0.30.1 255.255.255.248
          - ip ospf 1 area 0
          - no shutdown
        parents: interface GigabitEthernet0/0
    - name: Configure G1/0
      ios_config:
        lines:
          - ip address 11.0.30.1 255.255.255.252
          - ip ospf 1 area 0
          - no shutdown
        parents: interface GigabitEthernet1/0
- name: Configure R2 with subnets and OSPF
  hosts: R2
  gather_facts: false
  tasks:
    - name: Configure OSPF process
      ios_config:
        lines:
          - router ospf 1
    - name: Configure G0/0
      ios_config:
        lines:
          - ip address 10.0.30.2 255.255.255.248
          - ip ospf 1 area 0
          - no shutdown
        parents: interface GigabitEthernet0/0
    - name: Configure G1/0
      ios_config:
        lines:
          - ip address 11.0.30.2 255.255.255.252
          - ip ospf 1 area 0
          - no shutdown
        parents: interface GigabitEthernet1/0